"""Report generation module for InsightFlow AI."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from io import BytesIO
from typing import Any

import pandas as pd
from fpdf import FPDF


@dataclass
class ReportMetadata:
    title: str
    generated_at: str
    row_count: int
    column_count: int


class ReportGenerator:
    """Builds exportable reports from analysis results."""

    def build_metadata(self, title: str, row_count: int, column_count: int) -> ReportMetadata:
        return ReportMetadata(
            title=title,
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            row_count=row_count,
            column_count=column_count,
        )

    def to_markdown(self, metadata: ReportMetadata, sections: dict[str, str]) -> str:
        lines = [
            f"# {metadata.title}",
            "",
            f"**Generated:** {metadata.generated_at}",
            f"**Rows:** {metadata.row_count} | **Columns:** {metadata.column_count}",
            "",
        ]
        for heading, body in sections.items():
            lines.extend([f"## {heading}", "", body, ""])
        return "\n".join(lines)


def generate_summary_table(summary: dict[str, Any]) -> pd.DataFrame:
    """Create a summary table for display and export."""
    return pd.DataFrame(
        {
            "Metric": [
                "Rows",
                "Columns",
                "Memory",
                "Missing Values",
                "Duplicates",
                "Quality Score",
            ],
            "Value": [
                summary.get("rows", "N/A"),
                summary.get("columns", "N/A"),
                summary.get("memory", "N/A"),
                summary.get("missing_values", "N/A"),
                summary.get("duplicates", "N/A"),
                summary.get("quality_score", "N/A"),
            ],
        }
    )


def generate_pdf_report(
    metadata: ReportMetadata,
    sections: dict[str, str],
    summary_table: pd.DataFrame | None = None,
) -> bytes:
    """Create a multi-page PDF report with professional formatting."""
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_creator("InsightFlow AI")
    pdf.set_author("InsightFlow AI")
    pdf.set_title(metadata.title)

    def add_heading(text: str, level: int = 1) -> None:
        pdf.set_font("Helvetica", "B", 16 if level == 1 else 12)
        pdf.ln(3)
        pdf.multi_cell(0, 8, text)
        pdf.ln(1)

    def add_paragraph(text: str) -> None:
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, text or "N/A")
        pdf.ln(1)

    pdf.add_page()
    add_heading("InsightFlow AI")
    add_heading("Enterprise Data Analytics Report", level=2)
    add_paragraph(f"Generated: {metadata.generated_at}")
    add_paragraph(f"Rows: {metadata.row_count} | Columns: {metadata.column_count}")

    for heading, body in sections.items():
        if not body:
            continue
        add_heading(heading)
        add_paragraph(body)

    if summary_table is not None and not summary_table.empty:
        add_heading("Summary Table")
        pdf.set_font("Helvetica", "", 9)
        col_widths = [40, 50]
        headers = list(summary_table.columns)
        pdf.set_fill_color(40, 60, 120)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(col_widths[0], 7, headers[0], border=1, fill=True)
        pdf.cell(col_widths[1], 7, headers[1], border=1, fill=True)
        pdf.ln()
        pdf.set_text_color(0, 0, 0)
        for _, row in summary_table.iterrows():
            pdf.cell(col_widths[0], 6, str(row.iloc[0]), border=1)
            pdf.cell(col_widths[1], 6, str(row.iloc[1]), border=1)
            pdf.ln()
        pdf.ln(2)

    pdf_bytes = BytesIO()
    pdf.output(pdf_bytes)
    return pdf_bytes.getvalue()


def generate_markdown_report(
    metadata: ReportMetadata,
    sections: dict[str, str],
    summary_table: pd.DataFrame | None = None,
) -> str:
    """Generate a markdown report with the same structure as the PDF."""
    report = [
        f"# {metadata.title}",
        "",
        "## InsightFlow AI",
        "## Enterprise Data Analytics Report",
        "",
        f"- Generated: {metadata.generated_at}",
        f"- Rows: {metadata.row_count}",
        f"- Columns: {metadata.column_count}",
        "",
    ]

    for heading, body in sections.items():
        if body:
            report.extend([f"## {heading}", "", body, ""])

    if summary_table is not None and not summary_table.empty:
        report.extend(["## Summary Table", "", summary_table.to_markdown(index=False), ""])

    report.extend(["## Report Generated By", "", "InsightFlow AI", "", f"Generation Timestamp: {metadata.generated_at}"])
    return "\n".join(report)
